### ISSUE TITLE
Subheadings for the API documentation in nav

### ISSUE THREAD

**Issue by ghost** [OnePageCRM/OnePageCRM.github.io#1]
Add subheadings for the API doc in the nav.
Make them pop open and closed with the scrollspy.
See https://developers.facebook.com/docs/graph-api/using-graph-api or http://getbootstrap.com/components/ for examples

**Comment by CillianMyles** [comment]
Our shiny new API documentation has been released, and can be seen: https://developer.onepagecrm.com/api/
