### ISSUE TITLE
Wrong documentation for address_list type

### ISSUE THREAD

**Issue by joaomarceloods** [OnePageCRM/OnePageCRM.github.io#19]
In _Contacts >> Resource Fields_ `address_list` is documented as `string`, but it should be `array`.

http://developer.onepagecrm.com/#contacts

**Comment by CillianMyles** [comment]
Our shiny new API documentation has been released, and can be seen: https://developer.onepagecrm.com/api/

Thanks for having taken the time to open this issue, which has been solved by the new docs!
